from enum import Enum

class Neighborhood(str, Enum):
    NAmes = 'NAmes'
    CollgCr = 'CollgCr'
    OldTown = 'OldTown'
    Edwards = 'Edwards'
    Somerst = 'Somerst'
    Gilbert = 'Gilbert'
    NridgHt = 'NridgHt'
    Sawyer = 'Sawyer'
    NWAmes = 'NWAmes'
    SawyerW = 'SawyerW'
    BrkSide = 'BrkSide'
    Crawfor = 'Crawfor'
    Mitchel = 'Mitchel'
    NoRidge = 'NoRidge'
    Timber = 'Timber'
    IDOTRR = 'IDOTRR'
    ClearCr = 'ClearCr'
    StoneBr = 'StoneBr'
    SWISU = 'SWISU'
    MeadowV = 'MeadowV'
    Blmngtn = 'Blmngtn'
    BrDale = 'BrDale'
    Veenker = 'Veenker'
    NPkVill = 'NPkVill'
    Blueste = 'Blueste'

    other = 'other'